services:
  samba:
    image: registry.internal.dannyshih.net:5000/samba:v4.19.5
    container_name: samba
    build: .
    platform: linux/amd64
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "4445:445"
    environment:
      SAMBA_USER: media
      SAMBA_PASSWORD_FILE: /password.txt
    volumes:
      - ./password.txt:/password.txt
      - ./smb.conf:/etc/samba/smb.conf
      - samba_dev_lovegood:/shares/lovegood

volumes:
  samba_dev_lovegood:
